permalink: /:year-:month-:day-:slug

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post" # this defaults all pages to the page template 